# Generated by Django 3.1.1 on 2020-12-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajivdahalapp', '0005_auto_20201226_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
