# Generated by Django 3.1.1 on 2020-12-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rajivdahalapp', '0008_auto_20201227_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bannerimage',
            field=models.ImageField(blank=True, default='', upload_to='postimage'),
        ),
    ]
