# Generated by Django 3.1.1 on 2021-02-10 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rajivdahalapp', '0011_trendingpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='', upload_to='postimage')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.CharField(max_length=20000)),
                ('description', models.CharField(max_length=2000)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
